highlighter: rouge
themeColor: #7cbaff

title: S1MB10T3
email: S1MB10T3@pm.me
description: ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "S1MB10T3.net" # the base hostname & protocol for your site, e.g. http://example.com

plugins: [jekyll-paginate]

paginate: 6
paginate_path: "blog/page:num/"

# Build settings
markdown: kramdown
