highlighter: rouge
themeColor: #fff

title: S1MB10T3
email: S1MB10T3@pm.me
description: ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "S1MB10T3.net" # the base hostname & protocol for your site, e.g. http://example.com


collections:
  post:
    output: true
    permalink: /blog/:title
  gallery:
    output: true
    permalink: /:title
